adjust_temp: false
batch_size: 32
boltzmann_confs: 32
boltzmann_steps: 5
boltzmann_training: false
boltzmann_weight: false
cache: data/DRUGS/cache
data_dir: data/DRUGS/drugs/
dataset: drugs
in_edge_features: 4
in_node_features: 74
likelihood: full
limit_train_mols: 0
log_dir: .
lr: 0.001
max_radius: 5.0
n_epochs: 300
no_batch_norm: false
no_residual: false
ns: 32
num_conv_layers: 4
num_workers: 1
nv: 8
optimizer: adam
radius_embed_dim: 50
restart_dir: null
scale_by_sigma: true
scheduler: plateau
scheduler_patience: 20
seed: 2022
sigma_embed_dim: 32
sigma_max: 3.14
sigma_min: 0.031400000000000004
split_path: data/DRUGS/split.npy
std_pickles: data/DRUGS/standardized_pickles
temp: 300
use_second_order_repr: false
inference_steps: 20
ode: false
